image: paulwarfie/comp1110-2022-s1-gitlab-ci:0.1.0

stages:
  - checksum
  - compliance
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX"
  - export CP=src:/ass1/*:/shared/junit-platform-console-standalone-1.7.0.jar:$PATH_TO_FX/*
  - export JUNIT="java $JAVAFX_OPTIONS -jar /shared/junit-platform-console-standalone-1.7.0.jar --class-path src:/ass1/comp1110-ass1.jar --disable-banner"

checksum:
  tags:
    - comp1110
  stage: checksum
  script:
    - python3 /validate.py --integrity comp1110-ass1
  except:
    variables:
      - $CI_PROJECT_NAME =~ /.*-dev$/

admin:
  tags:
    - comp1110
  stage: compliance
  script:
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp1110/schemas/statement-of-originality.json ./originality.yml
  except:
    variables:
      - $CI_PROJECT_NAME =~ /.*-dev$/

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP src/comp1110/ass1/*.java
  artifacts:
    paths:
      - src/comp1110/ass1/*.class

task1:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.PositionConstructorTest
  allow_failure: true

task2:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.IsCellEmptyTest
  allow_failure: true

task3:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.GetOppositeTest
  allow_failure: true

task4:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.NewChallengeTest
  allow_failure: true

task5:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.ApplyDirectionTest
  allow_failure: true

task6:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.IsSolutionTest
  allow_failure: true

task7:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.ActionToStringTest
  allow_failure: true

task8:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.FoxCanMoveTest
  allow_failure: true

task9:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.FoxMakeMoveTest
  allow_failure: true

task10:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.RabbitMakeMoveTest
  allow_failure: true

task11:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.NextFoxPositionsTest
    - $JUNIT -c=comp1110.ass1.NextRabbitPositionsTest
  allow_failure: true

task12:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass1.SolveChallengeTest
  allow_failure: true
  
## Local Variables:
## mode: yaml
## End:
