package comp1110.ass1;

import org.junit.jupiter.api.*;

import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.junit.jupiter.api.Assertions.*;

@Timeout(value = 1000, unit = MILLISECONDS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)

public class FoxMakeMoveTest {

    @Test
    public void testSimple() {
        for (MakeMoveResult testCase : SIMPLE_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testConflictingDirection() {
        testSimple();
        for (int i = 12; i < Challenge.CHALLENGES.length; i++) {
            Challenge challenge = Challenge.CHALLENGES[i];
            Jumpin jumpin = new Jumpin(challenge);
            int numFoxes = Jumpin.getRelevantSubstring(challenge.getInitialState(), State.FOX).length() / 3;
            for (int j = 0; j < numFoxes; j++) {
                Fox fox = jumpin.getFoxes()[j];
                Direction conflictDir1 = Direction.values()[(fox.getDirection().ordinal() + 1) % 4];
                Direction conflictDir2 = Direction.values()[(fox.getDirection().ordinal() + 3) % 4];
                Position[] originalPos = new Position[]{fox.getHeadPosition(), fox.getTailPosition()};
                test(challenge.getInitialState(), conflictDir1, originalPos, fox, jumpin, false);
                test(challenge.getInitialState(), conflictDir2, originalPos, fox, jumpin, false);
                test(challenge.getInitialState(), conflictDir1, originalPos, fox, jumpin, false);
                test(challenge.getInitialState(), conflictDir2, originalPos, fox, jumpin, false);
            }
        }
    }

    @Test
    public void testConflictOnBoard() {
        testSimple();
        for (MakeMoveResult testCase : CONFLICT_BOARD_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testMixed() {
        for (MakeMoveResult testCase : MIXED_TEST_CASES) {
            test(testCase);
        }
    }

    private void test(MakeMoveResult testCase) {
        Jumpin jumpin = new Jumpin(testCase.challenge);
        for (int i = 0; i < testCase.expectedStates.length; i++) {
            String expState = testCase.expectedStates[i];
            Fox fox = jumpin.getFoxes()[testCase.idxs[i]];
            Direction dir = testCase.directions[i];
            Position[] expPos = testCase.expectedPositions[i];
            boolean expOutcome = testCase.outcomes[i];
            test(expState, dir, expPos, fox, jumpin, expOutcome);
        }
    }

    private void test(String expState, Direction dir, Position[] expPos, Fox fox, Jumpin jumpin, boolean expOutcome) {
        String previousState = jumpin.stateToString(false);
        boolean outcome = fox.makeMove(dir, jumpin);
        String descriptor = "For state " + previousState + ":\n" +
                "In challenge number " + jumpin.getChallenge().getProblemNumber() + ":\n" +
                "And fox " + fox + ":\n" +
                "Moving in direction " + dir + ":\n";
        assertEquals(expOutcome, outcome, descriptor + "Expected return value of fox.makeMove() " +
                "to return " + expOutcome + ", but instead got " + outcome + ".");
        String outState = jumpin.stateToString(false);
        assertEquals(expState, outState, descriptor + "Expected resulting state from applying " +
                "fox.makeMove() to be " + expState + ", but instead got " + outState + ".");
        Position head = fox.getHeadPosition();
        assertEquals(expPos[0], head, descriptor + "Expected the position of the fox's head after " +
                "applying fox.makeMove() to be (" + expPos[0].getX() + "," + expPos[0].getY() + "), but " +
                "instead got (" + head.getX() + "," + head.getY() + ").");
        Position tail = fox.getTailPosition();
        assertEquals(expPos[1], tail, descriptor + "Expected the position of the fox's tail after " +
                "applying fox.makeMove() to be (" + expPos[1].getX() + "," + expPos[1].getY() + "), but " +
                "instead got (" + tail.getX() + "," + tail.getY() + ").");
    }

    private final static MakeMoveResult[] SIMPLE_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[13], Direction.WEST,
                    "C30M122242FE11",
                    new Position[]{new Position(1,1), new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[14], Direction.SOUTH,
                    "C43M202223FS32",
                    new Position[]{new Position(3,2), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[15], Direction.NORTH,
                    "C10M010223FN12",
                    new Position[]{new Position(1,2), new Position(1,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.SOUTH,
                    "C03M410242FN11S31",
                    new Position[]{new Position(1,1), new Position(1,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.SOUTH,
                    "C03M410242FN10S32",
                    new Position[]{new Position(3,2), new Position(3,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[17], Direction.EAST,
                    "C34M023204FW31E13",
                    new Position[]{new Position(3,1), new Position(4,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[17], Direction.EAST,
                    "C34M023204FW21E23",
                    new Position[]{new Position(2,3), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[18], Direction.NORTH,
                    "C21M204223FS32",
                    new Position[]{new Position(3,2), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[19], Direction.NORTH,
                    "C10M022223FN12",
                    new Position[]{new Position(1,2), new Position(1,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[20], Direction.EAST,
                    "C30M023223FE21",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.NORTH,
                    "C13M142444FS31W33",
                    new Position[]{new Position(3,1), new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.WEST,
                    "C13M142444FS32W23",
                    new Position[]{new Position(2,3), new Position(3,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.EAST,
                    "C30M403224FE21N13",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.NORTH,
                    "C30M403224FE11N12",
                    new Position[]{new Position(1,2), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.NORTH,
                    "C41M402122FS31W33",
                    new Position[]{new Position(3,1), new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.WEST,
                    "C41M402122FS32W23",
                    new Position[]{new Position(2,3), new Position(3,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.SOUTH,
                    "B33G03M414244FS12N30",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.SOUTH,
                    "B33G03M414244FS11N31",
                    new Position[]{new Position(3,1), new Position(3,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[25], Direction.EAST,
                    "B31G22M1013FE21",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.EAST,
                    "B31G00M400304FE21S13",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.SOUTH,
                    "B31G00M400304FE11S14",
                    new Position[]{new Position(1,4), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.SOUTH,
                    "B42G11M3203FN13",
                    new Position[]{new Position(1,3), new Position(1,4)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.NORTH,
                    "B33G44M24FS31",
                    new Position[]{new Position(3,1), new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.SOUTH,
                    "B13G24M42FS12W31",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.WEST,
                    "B13G24M42FS11W21",
                    new Position[]{new Position(2,1), new Position(3,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.SOUTH,
                    "B44G31M012141FS12E23",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.EAST,
                    "B44G31M012141FS11E33",
                    new Position[]{new Position(3,3), new Position(2,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.EAST,
                    "B31G44M323334FE21N13",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.NORTH,
                    "B31G44M323334FE11N12",
                    new Position[]{new Position(1,2), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.SOUTH,
                    "B14G00M4021FS12N30",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.SOUTH,
                    "B14G00M4021FS11N31",
                    new Position[]{new Position(3,1), new Position(3,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.EAST,
                    "B32G31M1102FE23N33",
                    new Position[]{new Position(2,3), new Position(1,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[35], Direction.WEST,
                    "B00G33M301222FE11",
                    new Position[]{new Position(1,1), new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.SOUTH,
                    "C24M012204FS12E13",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.EAST,
                    "C24M012204FS11E23",
                    new Position[]{new Position(2,3), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.SOUTH,
                    "C44G03M202122FS12N30",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.SOUTH,
                    "C44G03M202122FS11N31",
                    new Position[]{new Position(3,1), new Position(3,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.EAST,
                    "C32B12G22M304233FE21W31",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.WEST,
                    "C32B12G22M304233FE11W21",
                    new Position[]{new Position(2,1), new Position(3,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.EAST,
                    "C31G14M201204FE23N33",
                    new Position[]{new Position(2,3), new Position(1,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.NORTH,
                    "C31G14M201204FE13N32",
                    new Position[]{new Position(3,2), new Position(3,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.SOUTH,
                    "C24B14M212304FS12",
                    new Position[]{new Position(1,2), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[41], Direction.SOUTH,
                    "C00B43M213132FS13",
                    new Position[]{new Position(1,3), new Position(1,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.NORTH,
                    "C13B41G14M223344FN10W21",
                    new Position[]{new Position(1,0), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.EAST,
                    "C42B23G03M00FW31S34",
                    new Position[]{new Position(3,1), new Position(4,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.NORTH,
                    "C42B23G03M00FW21S33",
                    new Position[]{new Position(3,3), new Position(3,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.SOUTH,
                    "C02B34G03M100111FN31",
                    new Position[]{new Position(3,1), new Position(3,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.WEST,
                    "C24B41M223223FE21",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.EAST,
                    "C40B31G34M2244FE21S13",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.SOUTH,
                    "C40B31G34M2244FE11S14",
                    new Position[]{new Position(1,4), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.EAST,
                    "C30B21G20M100122FW13",
                    new Position[]{new Position(1,3), new Position(2,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.SOUTH,
                    "C00B01G23M042444FE21S33",
                    new Position[]{new Position(3,3), new Position(3,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.EAST,
                    "C31B42G34M402304FE21S13",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.SOUTH,
                    "C31B42G34M402304FE11S14",
                    new Position[]{new Position(1,4), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.WEST,
                    "C41B30G10M010204FN11W03",
                    new Position[]{new Position(0,3), new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.SOUTH,
                    "C10B34G14M200113FS32",
                    new Position[]{new Position(3,2), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.NORTH,
                    "C22B03G23M210444FS32",
                    new Position[]{new Position(3,2), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.EAST,
                    "C03B14G41M402243FE21N31",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.SOUTH,
                    "C03B14G41M402243FE11N32",
                    new Position[]{new Position(3,2), new Position(3,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.WEST,
                    "C00B11G13M221444FW21E43",
                    new Position[]{new Position(2,1), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.WEST,
                    "C00B11G13M221444FW31E33",
                    new Position[]{new Position(3,3), new Position(2,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.NORTH,
                    "C22B02G10M404204FN30W33",
                    new Position[]{new Position(3,0), new Position(3,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.WEST,
                    "C22B02G10M404204FN31W23",
                    new Position[]{new Position(2,3), new Position(3,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.EAST,
                    "C31B42G03M302244FE21W23",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.EAST,
                    "C31B42G03M302244FE11W33",
                    new Position[]{new Position(3,3), new Position(4,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.EAST,
                    "C31B42G34M302203FE21",
                    new Position[]{new Position(2,1), new Position(1,1)},
                    true, 0),
    };

    private final static MakeMoveResult[] CONFLICT_BOARD_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.EAST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[14], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[15], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[17], Direction.WEST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[19], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[20], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.SOUTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[25], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.SOUTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.SOUTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.WEST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.SOUTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.EAST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.WEST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.SOUTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.EAST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.EAST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.NORTH, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.NORTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.EAST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.SOUTH, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.EAST, 1, true),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.WEST, 0, true),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.WEST, 0, true),
    };

    private final static MakeMoveResult[] MIXED_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[12], new Direction[]{Direction.NORTH, Direction.NORTH},
                    new String[]{"C21M301122FW31", "C21M301122FW31"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(4, 1)}, new Position[]{new Position(3, 1), new Position(4, 1)}},
                    new boolean[]{false, false},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[13], new Direction[]{Direction.EAST, Direction.EAST, Direction.EAST, Direction.WEST},
                    new String[]{"C30M122242FE31", "C30M122242FE41", "C30M122242FE41", "C30M122242FE31"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(2, 1)}, new Position[]{new Position(4, 1), new Position(3, 1)}, new Position[]{new Position(4, 1), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(2, 1)}},
                    new boolean[]{true, true, false, true},
                    new int[]{0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[14], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.SOUTH, Direction.EAST, Direction.SOUTH},
                    new String[]{"C43M202223FS32", "C43M202223FS33", "C43M202223FS34", "C43M202223FS34", "C43M202223FS34"},
                    new Position[][]{new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 3), new Position(3, 2)}, new Position[]{new Position(3, 4), new Position(3, 3)}, new Position[]{new Position(3, 4), new Position(3, 3)}, new Position[]{new Position(3, 4), new Position(3, 3)}},
                    new boolean[]{true, true, true, false, false},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[15], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.SOUTH},
                    new String[]{"C10M010223FN13", "C10M010223FN13", "C10M010223FN12", "C10M010223FN12", "C10M010223FN13"},
                    new Position[][]{new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 2), new Position(1, 3)}, new Position[]{new Position(1, 2), new Position(1, 3)}, new Position[]{new Position(1, 3), new Position(1, 4)}},
                    new boolean[]{false, false, true, false, true},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[16], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C03M410242FN10S31", "C03M410242FN10S32"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 2), new Position(3, 1)}},
                    new boolean[]{false, true},
                    new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[17], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.WEST, Direction.WEST},
                    new String[]{"C34M023204FW11E13", "C34M023204FW21E13", "C34M023204FW11E13", "C34M023204FW01E13", "C34M023204FW01E13"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(2, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(1, 1), new Position(2, 1)}, new Position[]{new Position(0, 1), new Position(1, 1)}, new Position[]{new Position(1, 3), new Position(0, 3)}},
                    new boolean[]{true, true, true, true, false},
                    new int[]{0, 0, 0, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[18], new Direction[]{Direction.EAST, Direction.SOUTH},
                    new String[]{"C21M204223FS33", "C21M204223FS34"},
                    new Position[][]{new Position[]{new Position(3, 3), new Position(3, 2)}, new Position[]{new Position(3, 4), new Position(3, 3)}},
                    new boolean[]{false, true},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[19], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.SOUTH, Direction.WEST},
                    new String[]{"C10M022223FN13", "C10M022223FN13", "C10M022223FN13", "C10M022223FN13"},
                    new Position[][]{new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 3), new Position(1, 4)}},
                    new boolean[]{false, false, false, false},
                    new int[]{0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[20], new Direction[]{Direction.SOUTH, Direction.WEST},
                    new String[]{"C30M023223FE11", "C30M023223FE11"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 1), new Position(0, 1)}},
                    new boolean[]{false, false},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[21], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.SOUTH, Direction.NORTH},
                    new String[]{"C13M142444FS32W33", "C13M142444FS32W33", "C13M142444FS32W33", "C13M142444FS31W33"},
                    new Position[][]{new Position[]{new Position(3, 3), new Position(4, 3)}, new Position[]{new Position(3, 3), new Position(4, 3)}, new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(3, 0)}},
                    new boolean[]{false, false, false, true},
                    new int[]{1, 1, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[22], new Direction[]{Direction.EAST, Direction.EAST, Direction.WEST, Direction.NORTH},
                    new String[]{"C30M403224FE21N13", "C30M403224FE21N13", "C30M403224FE11N13", "C30M403224FE11N12"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 2), new Position(1, 3)}},
                    new boolean[]{true, false, true, true},
                    new int[]{0, 1, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[23], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH},
                    new String[]{"C41M402122FS31W33", "C41M402122FS32W33", "C41M402122FS32W33"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 3), new Position(4, 3)}},
                    new boolean[]{true, true, false},
                    new int[]{0, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[24], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.EAST, Direction.WEST},
                    new String[]{"B33G03M414244FS11N30", "B33G03M414244FS12N30", "B33G03M414244FS12N30", "B33G03M414244FS12N30"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}},
                    new boolean[]{false, true, false, false},
                    new int[]{0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[25], new Direction[]{Direction.EAST, Direction.NORTH, Direction.SOUTH, Direction.WEST, Direction.WEST},
                    new String[]{"B31G22M1013FE21", "B31G22M1013FE21", "B31G22M1013FE21", "B31G22M1013FE11", "B31G22M1013FE11"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 1), new Position(0, 1)}},
                    new boolean[]{true, false, false, true, false},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[26], new Direction[]{Direction.WEST, Direction.NORTH, Direction.NORTH, Direction.EAST, Direction.NORTH},
                    new String[]{"B31G00M400304FE11S13", "B31G00M400304FE11S13", "B31G00M400304FE11S13", "B31G00M400304FE21S13", "B31G00M400304FE21S13"},
                    new Position[][]{new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(1, 3), new Position(1, 2)}},
                    new boolean[]{false, false, false, true, false},
                    new int[]{1, 0, 1, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[27], new Direction[]{Direction.EAST, Direction.SOUTH},
                    new String[]{"B42G11M3203FN12", "B42G11M3203FN13"},
                    new Position[][]{new Position[]{new Position(1, 2), new Position(1, 3)}, new Position[]{new Position(1, 3), new Position(1, 4)}},
                    new boolean[]{false, true},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[28], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.NORTH},
                    new String[]{"B33G44M24FS31", "B33G44M24FS32", "B33G44M24FS31", "B33G44M24FS31"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 1), new Position(3, 0)}},
                    new boolean[]{true, true, true, false},
                    new int[]{0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[29], new Direction[]{Direction.WEST, Direction.SOUTH, Direction.NORTH},
                    new String[]{"B13G24M42FS11W21", "B13G24M42FS12W21", "B13G24M42FS11W21"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 1), new Position(1, 0)}},
                    new boolean[]{true, true, true},
                    new int[]{1, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[30], new Direction[]{Direction.NORTH, Direction.NORTH, Direction.SOUTH},
                    new String[]{"B40G32M102022FS34", "B40G32M102022FS34", "B40G32M102022FS34"},
                    new Position[][]{new Position[]{new Position(3, 4), new Position(3, 3)}, new Position[]{new Position(3, 4), new Position(3, 3)}, new Position[]{new Position(3, 4), new Position(3, 3)}},
                    new boolean[]{false, false, false},
                    new int[]{0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[31], new Direction[]{Direction.WEST, Direction.EAST, Direction.SOUTH},
                    new String[]{"B44G31M012141FS11E23", "B44G31M012141FS11E33", "B44G31M012141FS12E33"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(3, 3), new Position(2, 3)}, new Position[]{new Position(1, 2), new Position(1, 1)}},
                    new boolean[]{false, true, true},
                    new int[]{0, 1, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[32], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.WEST, Direction.NORTH},
                    new String[]{"B31G44M323334FE11N13", "B31G44M323334FE11N13", "B31G44M323334FE11N13", "B31G44M323334FE11N12"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 3), new Position(1, 4)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 2), new Position(1, 3)}},
                    new boolean[]{false, false, false, true},
                    new int[]{0, 1, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[33], new Direction[]{Direction.NORTH, Direction.WEST, Direction.EAST},
                    new String[]{"B14G00M4021FS11N30", "B14G00M4021FS11N30", "B14G00M4021FS11N30"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(3, 0), new Position(3, 1)}, new Position[]{new Position(3, 0), new Position(3, 1)}},
                    new boolean[]{false, false, false},
                    new int[]{0, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[34], new Direction[]{Direction.EAST, Direction.EAST},
                    new String[]{"B32G31M1102FE23N33", "B32G31M1102FE23N33"},
                    new Position[][]{new Position[]{new Position(2, 3), new Position(1, 3)}, new Position[]{new Position(3, 3), new Position(3, 4)}},
                    new boolean[]{true, false},
                    new int[]{0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[35], new Direction[]{Direction.SOUTH, Direction.EAST},
                    new String[]{"B00G33M301222FE21", "B00G33M301222FE31"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(3, 1), new Position(2, 1)}},
                    new boolean[]{false, true},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[36], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.WEST},
                    new String[]{"C24M012204FS12E13", "C24M012204FS12E13", "C24M012204FS12E13"},
                    new Position[][]{new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}},
                    new boolean[]{true, false, false},
                    new int[]{0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[37], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.NORTH},
                    new String[]{"C44G03M202122FS11N30", "C44G03M202122FS12N30", "C44G03M202122FS11N30", "C44G03M202122FS11N30"},
                    new Position[][]{new Position[]{new Position(3, 0), new Position(3, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(3, 0), new Position(3, 1)}},
                    new boolean[]{false, true, true, false},
                    new int[]{1, 0, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[38], new Direction[]{Direction.EAST, Direction.WEST, Direction.EAST},
                    new String[]{"C32B12G22M304233FE11W31", "C32B12G22M304233FE11W21", "C32B12G22M304233FE11W31"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(4, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(4, 1)}},
                    new boolean[]{false, true, true},
                    new int[]{1, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[39], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.NORTH, Direction.EAST},
                    new String[]{"C31G14M201204FE13N33", "C31G14M201204FE23N33", "C31G14M201204FE13N33", "C31G14M201204FE13N32", "C31G14M201204FE23N32"},
                    new Position[][]{new Position[]{new Position(3, 3), new Position(3, 4)}, new Position[]{new Position(2, 3), new Position(1, 3)}, new Position[]{new Position(1, 3), new Position(0, 3)}, new Position[]{new Position(3, 2), new Position(3, 3)}, new Position[]{new Position(2, 3), new Position(1, 3)}},
                    new boolean[]{false, true, true, true, true},
                    new int[]{1, 0, 0, 1, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[40], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C24B14M212304FS11", "C24B14M212304FS12"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(1, 2), new Position(1, 1)}},
                    new boolean[]{false, true},
                    new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[41], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.WEST, Direction.NORTH, Direction.WEST},
                    new String[]{"C00B43M213132FS11", "C00B43M213132FS12", "C00B43M213132FS12", "C00B43M213132FS11", "C00B43M213132FS11"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 2), new Position(1, 1)}, new Position[]{new Position(1, 1), new Position(1, 0)}, new Position[]{new Position(1, 1), new Position(1, 0)}},
                    new boolean[]{true, true, false, true, false},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[42], new Direction[]{Direction.EAST, Direction.WEST, Direction.WEST, Direction.EAST, Direction.EAST},
                    new String[]{"B41G11M122232FW21", "B41G11M122232FW21", "B41G11M122232FW21", "B41G11M122232FW21", "B41G11M122232FW21"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}},
                    new boolean[]{false, false, false, false, false},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[43], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.NORTH, Direction.NORTH},
                    new String[]{"C13B41G14M223344FN11W21", "C13B41G14M223344FN11W21", "C13B41G14M223344FN10W21", "C13B41G14M223344FN10W21"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(1, 2)}, new Position[]{new Position(1, 1), new Position(1, 2)}, new Position[]{new Position(1, 0), new Position(1, 1)}, new Position[]{new Position(2, 1), new Position(3, 1)}},
                    new boolean[]{false, false, true, false},
                    new int[]{0, 0, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[44], new Direction[]{Direction.WEST, Direction.SOUTH, Direction.WEST},
                    new String[]{"C42B23G03M00FW11S34", "C42B23G03M00FW11S34", "C42B23G03M00FW11S34"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(2, 1)}, new Position[]{new Position(3, 4), new Position(3, 3)}, new Position[]{new Position(3, 4), new Position(3, 3)}},
                    new boolean[]{true, false, false},
                    new int[]{0, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[45], new Direction[]{Direction.SOUTH, Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.NORTH},
                    new String[]{"C02B34G03M100111FN31", "C02B34G03M100111FN30", "C02B34G03M100111FN31", "C02B34G03M100111FN30", "C02B34G03M100111FN30"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 2)}, new Position[]{new Position(3, 0), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(3, 2)}, new Position[]{new Position(3, 0), new Position(3, 1)}, new Position[]{new Position(3, 0), new Position(3, 1)}},
                    new boolean[]{true, true, true, true, false},
                    new int[]{0, 0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[46], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.SOUTH},
                    new String[]{"C24B41M223223FE31", "C24B41M223223FE31", "C24B41M223223FE31"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(2, 1)}, new Position[]{new Position(3, 1), new Position(2, 1)}, new Position[]{new Position(3, 1), new Position(2, 1)}},
                    new boolean[]{false, false, false},
                    new int[]{0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[48], new Direction[]{Direction.NORTH, Direction.WEST, Direction.NORTH, Direction.NORTH, Direction.EAST},
                    new String[]{"C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", "C40B31G34M2244FE21S13"},
                    new Position[][]{new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(2, 1), new Position(1, 1)}},
                    new boolean[]{false, false, false, false, true},
                    new int[]{1, 0, 1, 1, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[49], new Direction[]{Direction.WEST, Direction.WEST, Direction.EAST},
                    new String[]{"C30B21G20M100122FW03", "C30B21G20M100122FW03", "C30B21G20M100122FW13"},
                    new Position[][]{new Position[]{new Position(0, 3), new Position(1, 3)}, new Position[]{new Position(0, 3), new Position(1, 3)}, new Position[]{new Position(1, 3), new Position(2, 3)}},
                    new boolean[]{false, false, true},
                    new int[]{0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[50], new Direction[]{Direction.EAST, Direction.NORTH, Direction.NORTH, Direction.NORTH},
                    new String[]{"C00B01G23M042444FE21S32", "C00B01G23M042444FE21S31", "C00B01G23M042444FE21S31", "C00B01G23M042444FE21S31"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 1), new Position(3, 0)}},
                    new boolean[]{false, true, false, false},
                    new int[]{0, 1, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[51], new Direction[]{Direction.NORTH, Direction.NORTH, Direction.WEST, Direction.NORTH},
                    new String[]{"C31B42G34M402304FE11S13", "C31B42G34M402304FE11S13", "C31B42G34M402304FE11S13", "C31B42G34M402304FE11S13"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(1, 3), new Position(1, 2)}, new Position[]{new Position(1, 3), new Position(1, 2)}},
                    new boolean[]{false, false, false, false},
                    new int[]{0, 1, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[52], new Direction[]{Direction.WEST, Direction.NORTH, Direction.NORTH, Direction.SOUTH},
                    new String[]{"C41B30G10M010204FN11W03", "C41B30G10M010204FN11W03", "C41B30G10M010204FN11W03", "C41B30G10M010204FN11W03"},
                    new Position[][]{new Position[]{new Position(0, 3), new Position(1, 3)}, new Position[]{new Position(1, 1), new Position(1, 2)}, new Position[]{new Position(1, 1), new Position(1, 2)}, new Position[]{new Position(1, 1), new Position(1, 2)}},
                    new boolean[]{true, false, false, false},
                    new int[]{1, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[53], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.SOUTH},
                    new String[]{"C10B34G14M200113FS31", "C10B34G14M200113FS32", "C10B34G14M200113FS31", "C10B34G14M200113FS32"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 1), new Position(3, 0)}, new Position[]{new Position(3, 2), new Position(3, 1)}},
                    new boolean[]{false, true, true, true},
                    new int[]{0, 0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.SOUTH},
                    new String[]{"C22B03G23M210444FS32", "C22B03G23M210444FS33", "C22B03G23M210444FS34"},
                    new Position[][]{new Position[]{new Position(3, 2), new Position(3, 1)}, new Position[]{new Position(3, 3), new Position(3, 2)}, new Position[]{new Position(3, 4), new Position(3, 3)}},
                    new boolean[]{true, true, true},
                    new int[]{0, 0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[55], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.EAST},
                    new String[]{"C03B14G41M402243FE11N32", "C03B14G41M402243FE11N33", "C03B14G41M402243FE11N33"},
                    new Position[][]{new Position[]{new Position(3, 2), new Position(3, 3)}, new Position[]{new Position(3, 3), new Position(3, 4)}, new Position[]{new Position(3, 3), new Position(3, 4)}},
                    new boolean[]{true, true, false},
                    new int[]{1, 1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[56], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.WEST, Direction.NORTH},
                    new String[]{"C00B11G13M221444FW21E43", "C00B11G13M221444FW21E43", "C00B11G13M221444FW21E33", "C00B11G13M221444FW21E33", "C00B11G13M221444FW21E33"},
                    new Position[][]{new Position[]{new Position(2, 1), new Position(3, 1)}, new Position[]{new Position(4, 3), new Position(3, 3)}, new Position[]{new Position(3, 3), new Position(2, 3)}, new Position[]{new Position(3, 3), new Position(2, 3)}, new Position[]{new Position(2, 1), new Position(3, 1)}},
                    new boolean[]{true, false, true, false, false},
                    new int[]{0, 1, 1, 1, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[57], new Direction[]{Direction.SOUTH, Direction.NORTH, Direction.NORTH},
                    new String[]{"C22B02G10M404204FN31W33", "C22B02G10M404204FN31W33", "C22B02G10M404204FN30W33"},
                    new Position[][]{new Position[]{new Position(3, 1), new Position(3, 2)}, new Position[]{new Position(3, 3), new Position(4, 3)}, new Position[]{new Position(3, 0), new Position(3, 1)}},
                    new boolean[]{false, false, true},
                    new int[]{0, 1, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[58], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.EAST, Direction.NORTH},
                    new String[]{"C31B42G03M302244FE11W23", "C31B42G03M302244FE11W33", "C31B42G03M302244FE11W23", "C31B42G03M302244FE21W23", "C31B42G03M302244FE21W23"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(3, 3), new Position(4, 3)}, new Position[]{new Position(2, 3), new Position(3, 3)}, new Position[]{new Position(2, 1), new Position(1, 1)}, new Position[]{new Position(2, 3), new Position(3, 3)}},
                    new boolean[]{false, true, true, true, false},
                    new int[]{0, 1, 1, 0, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[59], new Direction[]{Direction.WEST, Direction.WEST, Direction.WEST},
                    new String[]{"C31B42G34M302203FE11", "C31B42G34M302203FE11", "C31B42G34M302203FE11"},
                    new Position[][]{new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 1), new Position(0, 1)}, new Position[]{new Position(1, 1), new Position(0, 1)}},
                    new boolean[]{false, false, false},
                    new int[]{0, 0, 0})
    };

}
