package comp1110.ass1;

import org.junit.jupiter.api.*;

import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Timeout(value = 1000, unit = MILLISECONDS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)

public class RabbitMakeMoveTest {

    @Test
    public void testNoNeighbour() {
        testSimple();
        for (MakeMoveResult testCase : NO_NEIGHBOUR_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testOffBoardNeighbouring() {
        testSimple();
        for (MakeMoveResult testCase : OFF_BOARD_NEIGHBOUR_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testOffBoardJump() {
        testSimple();
        for (MakeMoveResult testCase : JUMP_OFF_BOARD_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testSimple() {
        for (MakeMoveResult testCase : SIMPLE_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testJumpOverMultipleObstacles() {
        for (MakeMoveResult testCase : MULTIPLE_OBJECT_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testSimpleMoveAndInverse() {
        for (MakeMoveResult testCase : SIMPLE_INVERSE_TEST_CASES) {
            test(testCase);
        }
    }

    @Test
    public void testMixed() {
        for (MakeMoveResult testCase : MIXED_TEST_CASES) {
            test(testCase);
        }
    }

    private void test(MakeMoveResult testCase) {
        Jumpin jumpin = new Jumpin(testCase.challenge);
        for (int i = 0; i < testCase.expectedStates.length; i++) {
            String expState = testCase.expectedStates[i];
            Rabbit rabbit = jumpin.getRabbits()[testCase.idxs[i]];
            Direction dir = testCase.directions[i];
            Position expPos = testCase.expectedPositions[i][0];
            boolean expOutcome = testCase.outcomes[i];
            test(expState, dir, expPos, rabbit, jumpin, expOutcome);
        }
    }

    private void test(String expState, Direction dir, Position expPos, Rabbit rabbit, Jumpin jumpin, boolean expOutcome) {
        String previousState = jumpin.stateToString(false);
        boolean outcome = rabbit.makeMove(dir, jumpin);
        String descriptor = "For state " + previousState + ":\n" +
                "In challenge number " + jumpin.getChallenge().getProblemNumber() + ":\n" +
                "And rabbit " + rabbit + ":\n" +
                "Moving in direction " + dir + ":\n";
        assertEquals(expOutcome, outcome, descriptor + "Expected return value of rabbit.makeMove() " +
                "to return " + expOutcome + ", but instead got " + outcome + ".");
        String outState = jumpin.stateToString(false);
        assertEquals(expState, outState, descriptor + "Expected resulting state from applying " +
                "rabbit.makeMove() to be " + expState + ", but instead got " + outState + ".");
        Position pos = rabbit.getPosition();
        assertEquals(expPos, pos, descriptor + "Expected the position of the rabbit after " +
                "applying rabbit.makeMove() to be (" + pos.getX() + "," + pos.getY() + "), but " +
                "instead got (" + pos.getX() + "," + pos.getY() + ").");
    }

    private final static MakeMoveResult[] NO_NEIGHBOUR_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[0], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[2], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[2], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[3], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[3], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[4], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[4], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[5], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[5], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[6], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[6], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[13], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[14], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[15], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[17], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[18], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[19], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[20], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[25], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[25], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[35], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[35], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[41], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[41], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.EAST, 2, false),
    };

    private final static MakeMoveResult[] OFF_BOARD_NEIGHBOUR_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[2], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[2], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[3], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[3], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[4], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[4], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[5], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[6], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[13], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[14], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[15], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[17], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[19], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[20], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[24], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[29], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[35], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[36], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[37], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[41], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[41], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[51], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.WEST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.SOUTH, 2, false),
    };

    private final static MakeMoveResult[] JUMP_OFF_BOARD_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[18], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[21], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[22], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[31], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.WEST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.WEST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.EAST, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.SOUTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[48], Direction.EAST, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.NORTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.SOUTH, 1, false),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.NORTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[56], Direction.SOUTH, 2, false),
            new MakeMoveResult(Challenge.CHALLENGES[57], Direction.EAST, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[58], Direction.NORTH, 0, false),
            new MakeMoveResult(Challenge.CHALLENGES[59], Direction.NORTH, 0, false),
    };

    private final static MakeMoveResult[] SIMPLE_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[0], Direction.NORTH,
                    "C30M102031", new Position[]{new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.SOUTH,
                    "C42B20M304132", new Position[]{new Position(4,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[2], Direction.NORTH,
                    "C10B22M302123", new Position[]{new Position(2,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[3], Direction.SOUTH,
                    "C14B04M032334", new Position[]{new Position(0,4)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[5], Direction.EAST,
                    "C20B32M102112", new Position[]{new Position(2,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[6], Direction.WEST,
                    "C24B32M132334", new Position[]{new Position(2,4)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[7], Direction.NORTH,
                    "C22B40G02M411232", new Position[]{new Position(4,0)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.WEST,
                    "C24B20G00M103021", new Position[]{new Position(2,0)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[8], Direction.EAST,
                    "C24B40G20M103021", new Position[]{new Position(2,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[9], Direction.SOUTH,
                    "C40B20G02M103001", new Position[]{new Position(0,2)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[10], Direction.EAST,
                    "C42B30G20M102133", new Position[]{new Position(2,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.SOUTH,
                    "C42B14G02M132434", new Position[]{new Position(1,4)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[11], Direction.EAST,
                    "C42B12G22M132434", new Position[]{new Position(2,2)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.SOUTH,
                    "C23M301122FW31", new Position[]{new Position(2,3)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[12], Direction.WEST,
                    "C01M301122FW31", new Position[]{new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[16], Direction.NORTH,
                    "C01M410242FN10S31", new Position[]{new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[26], Direction.SOUTH,
                    "B31G02M400304FE11S13", new Position[]{new Position(0,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.WEST,
                    "B22G11M3203FN12", new Position[]{new Position(2,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[30], Direction.WEST,
                    "B40G12M102022FS34", new Position[]{new Position(1,2)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[32], Direction.WEST,
                    "B31G24M323334FE11N13", new Position[]{new Position(2,4)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[33], Direction.EAST,
                    "B14G20M4021FS11N30", new Position[]{new Position(2,0)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[34], Direction.NORTH,
                    "B30G31M1102FE13N33", new Position[]{new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.SOUTH,
                    "C34B12G22M304233FE11W31", new Position[]{new Position(3,4)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.NORTH,
                    "C32B10G22M304233FE11W31", new Position[]{new Position(1,0)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.WEST,
                    "C32B12G02M304233FE11W31", new Position[]{new Position(0,2)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.NORTH,
                    "C22B14M212304FS11", new Position[]{new Position(2,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[40], Direction.EAST,
                    "C24B34M212304FS11", new Position[]{new Position(3,4)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.SOUTH,
                    "B41G13M122232FW21", new Position[]{new Position(1,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[44], Direction.EAST,
                    "C42B43G03M00FW21S34", new Position[]{new Position(4,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.NORTH,
                    "C00B34G03M100111FN30", new Position[]{new Position(0,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.SOUTH,
                    "C04B34G03M100111FN30", new Position[]{new Position(0,4)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.SOUTH,
                    "C22B03G40M301121", new Position[]{new Position(2,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.SOUTH,
                    "C30B23G20M100122FW03", new Position[]{new Position(2,3)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.EAST,
                    "C30B21G40M100122FW03", new Position[]{new Position(4,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.WEST,
                    "C30B21G00M100122FW03", new Position[]{new Position(0,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.SOUTH,
                    "C02B01G23M042444FE21S32", new Position[]{new Position(0,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.NORTH,
                    "C10B34G12M200113FS31", new Position[]{new Position(1,2)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.NORTH,
                    "C20B03G23M210444FS33", new Position[]{new Position(2,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.EAST,
                    "C42B03G23M210444FS33", new Position[]{new Position(4,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.SOUTH,
                    "C24B03G23M210444FS33", new Position[]{new Position(2,4)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.EAST,
                    "C22B03G43M210444FS33", new Position[]{new Position(4,3)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[55], Direction.WEST,
                    "C03B14G21M402243FE11N31", new Position[]{new Position(2,1)},
                    true, 2),
    };

    private final static MakeMoveResult[] MULTIPLE_OBJECT_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[1], Direction.WEST,
                    "C10B20M304132", new Position[]{new Position(1,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[4], Direction.NORTH,
                    "C01B20M110203", new Position[]{new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[23], Direction.WEST,
                    "C11M402122FS32W33", new Position[]{new Position(1,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[27], Direction.SOUTH,
                    "B42G14M3203FN12", new Position[]{new Position(1,4)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[28], Direction.NORTH,
                    "B30G44M24FS32", new Position[]{new Position(3,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[38], Direction.WEST,
                    "C02B12G22M304233FE11W31", new Position[]{new Position(0,2)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[39], Direction.NORTH,
                    "C31G11M201204FE13N33", new Position[]{new Position(1,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[42], Direction.WEST,
                    "B01G11M122232FW21", new Position[]{new Position(0,1)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.NORTH,
                    "C10B41G14M223344FN11W21", new Position[]{new Position(1,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.WEST,
                    "C13B01G14M223344FN11W21", new Position[]{new Position(0,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[43], Direction.NORTH,
                    "C13B41G10M223344FN11W21", new Position[]{new Position(1,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[45], Direction.NORTH,
                    "C02B34G00M100111FN30", new Position[]{new Position(0,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.NORTH,
                    "C20B41M223223FE31", new Position[]{new Position(2,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[46], Direction.WEST,
                    "C24B11M223223FE31", new Position[]{new Position(1,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[47], Direction.WEST,
                    "C20B03G10M301121", new Position[]{new Position(1,0)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.WEST,
                    "C00B21G20M100122FW03", new Position[]{new Position(0,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[49], Direction.SOUTH,
                    "C30B21G23M100122FW03", new Position[]{new Position(2,3)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[50], Direction.EAST,
                    "C00B41G23M042444FE21S32", new Position[]{new Position(4,1)},
                    true, 1),
            new MakeMoveResult(Challenge.CHALLENGES[52], Direction.SOUTH,
                    "C41B30G14M010204FN11W13", new Position[]{new Position(1,4)},
                    true, 2),
            new MakeMoveResult(Challenge.CHALLENGES[53], Direction.EAST,
                    "C40B34G14M200113FS31", new Position[]{new Position(4,0)},
                    true, 0),
            new MakeMoveResult(Challenge.CHALLENGES[54], Direction.NORTH,
                    "C22B03G20M210444FS33", new Position[]{new Position(2,0)},
                    true, 2),
    };

    private final static MakeMoveResult[] SIMPLE_INVERSE_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[0], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C30M102031", "C32M102031"}, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[1], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C42B20M304132", "C40B20M304132"}, new Position[][]{new Position[]{new Position(4,2)}, new Position[]{new Position(4,0)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[2], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C10B22M302123", "C10B24M302123"}, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(2,4)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[3], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C14B04M032334", "C14B02M032334"}, new Position[][]{new Position[]{new Position(0,4)}, new Position[]{new Position(0,2)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[5], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C20B32M102112", "C00B32M102112"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[6], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C24B32M132334", "C44B32M132334"}, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(4,4)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[7], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C22B40G02M411232", "C22B42G02M411232"}, new Position[][]{new Position[]{new Position(4,0)}, new Position[]{new Position(4,2)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[8], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C24B20G00M103021", "C24B40G00M103021"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(4,0)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[8], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C24B40G20M103021", "C24B40G00M103021"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[9], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C40B20G02M103001", "C40B20G00M103001"}, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[10], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C42B30G20M102133", "C42B30G00M102133"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[11], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C42B14G02M132434", "C42B12G02M132434"}, new Position[][]{new Position[]{new Position(1,4)}, new Position[]{new Position(1,2)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[11], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C42B12G22M132434", "C42B12G02M132434"}, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(0,2)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[12], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C23M301122FW31", "C21M301122FW31"}, new Position[][]{new Position[]{new Position(2,3)}, new Position[]{new Position(2,1)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[12], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C01M301122FW31", "C21M301122FW31"}, new Position[][]{new Position[]{new Position(0,1)}, new Position[]{new Position(2,1)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[16], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C01M410242FN10S31", "C03M410242FN10S31"}, new Position[][]{new Position[]{new Position(0,1)}, new Position[]{new Position(0,3)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[26], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"B31G02M400304FE11S13", "B31G00M400304FE11S13"}, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[27], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"B22G11M3203FN12", "B42G11M3203FN12"}, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(4,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[30], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"B40G12M102022FS34", "B40G32M102022FS34"}, new Position[][]{new Position[]{new Position(1,2)}, new Position[]{new Position(3,2)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[32], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"B31G24M323334FE11N13", "B31G44M323334FE11N13"}, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(4,4)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[33], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"B14G20M4021FS11N30", "B14G00M4021FS11N30"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[34], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"B30G31M1102FE13N33", "B32G31M1102FE13N33"}, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[38], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C34B12G22M304233FE11W31", "C32B12G22M304233FE11W31"}, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(3,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[38], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C32B10G22M304233FE11W31", "C32B12G22M304233FE11W31"}, new Position[][]{new Position[]{new Position(1,0)}, new Position[]{new Position(1,2)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[38], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C32B12G02M304233FE11W31", "C32B12G22M304233FE11W31"}, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(2,2)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[40], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C22B14M212304FS11", "C24B14M212304FS11"}, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(2,4)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[40], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C24B34M212304FS11", "C24B14M212304FS11"}, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(1,4)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[42], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"B41G13M122232FW21", "B41G11M122232FW21"}, new Position[][]{new Position[]{new Position(1,3)}, new Position[]{new Position(1,1)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[44], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C42B43G03M00FW21S34", "C42B23G03M00FW21S34"}, new Position[][]{new Position[]{new Position(4,3)}, new Position[]{new Position(2,3)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[45], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C00B34G03M100111FN30", "C02B34G03M100111FN30"}, new Position[][]{new Position[]{new Position(0,0)}, new Position[]{new Position(0,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[45], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C04B34G03M100111FN30", "C02B34G03M100111FN30"}, new Position[][]{new Position[]{new Position(0,4)}, new Position[]{new Position(0,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[47], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C22B03G40M301121", "C20B03G40M301121"}, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(2,0)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[49], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C30B23G20M100122FW03", "C30B21G20M100122FW03"}, new Position[][]{new Position[]{new Position(2,3)}, new Position[]{new Position(2,1)}},
                    new boolean[]{true, true}, new int[]{1, 1}),
            new MakeMoveResult(Challenge.CHALLENGES[49], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C30B21G40M100122FW03", "C30B21G20M100122FW03"}, new Position[][]{new Position[]{new Position(4,0)}, new Position[]{new Position(2,0)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[49], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C30B21G00M100122FW03", "C30B21G20M100122FW03"}, new Position[][]{new Position[]{new Position(0,0)}, new Position[]{new Position(2,0)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[50], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C02B01G23M042444FE21S32", "C00B01G23M042444FE21S32"}, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(0,0)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[53], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C10B34G12M200113FS31", "C10B34G14M200113FS31"}, new Position[][]{new Position[]{new Position(1,2)}, new Position[]{new Position(1,4)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.NORTH, Direction.SOUTH},
                    new String[]{"C20B03G23M210444FS33", "C22B03G23M210444FS33"}, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(2,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C42B03G23M210444FS33", "C22B03G23M210444FS33"}, new Position[][]{new Position[]{new Position(4,2)}, new Position[]{new Position(2,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.SOUTH, Direction.NORTH},
                    new String[]{"C24B03G23M210444FS33", "C22B03G23M210444FS33"}, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(2,2)}},
                    new boolean[]{true, true}, new int[]{0, 0}),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.EAST, Direction.WEST},
                    new String[]{"C22B03G43M210444FS33", "C22B03G23M210444FS33"}, new Position[][]{new Position[]{new Position(4,3)}, new Position[]{new Position(2,3)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
            new MakeMoveResult(Challenge.CHALLENGES[55], new Direction[]{Direction.WEST, Direction.EAST},
                    new String[]{"C03B14G21M402243FE11N31", "C03B14G41M402243FE11N31"}, new Position[][]{new Position[]{new Position(2,1)}, new Position[]{new Position(4,1)}},
                    new boolean[]{true, true}, new int[]{2, 2}),
    };

    private final static MakeMoveResult[] MIXED_TEST_CASES = new MakeMoveResult[]{
            new MakeMoveResult(Challenge.CHALLENGES[0], new Direction[]{Direction.NORTH, Direction.WEST, Direction.EAST, },
                    new String[]{"C30M102031", "C00M102031", "C30M102031", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(0,0)}, new Position[]{new Position(3,0)}, },
                    new boolean[]{true, true, true, }, new int[]{0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[1], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.EAST, },
                    new String[]{"C42B20M304132", "C22B20M304132", "C22B40M304132", }, new Position[][]{new Position[]{new Position(4,2)}, new Position[]{new Position(2,2)}, new Position[]{new Position(4,0)}, },
                    new boolean[]{true, true, true, }, new int[]{0, 0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[2], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.WEST, Direction.EAST, },
                    new String[]{"C10B22M302123", "C10B22M302123", "C10B22M302123", "C10B22M302123", }, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, },
                    new boolean[]{true, false, false, false, }, new int[]{1, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[3], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.NORTH, Direction.NORTH, },
                    new String[]{"C14B04M032334", "C14B04M032334", "C14B02M032334", "C14B02M032334", }, new Position[][]{new Position[]{new Position(0,4)}, new Position[]{new Position(1,4)}, new Position[]{new Position(0,2)}, new Position[]{new Position(1,4)}, },
                    new boolean[]{true, false, true, false, }, new int[]{1, 0, 1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[4], new Direction[]{Direction.NORTH, Direction.NORTH, Direction.NORTH, },
                    new String[]{"C04B20M110203", "C01B20M110203", "C01B20M110203", }, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(0,1)}, new Position[]{new Position(2,0)}, },
                    new boolean[]{false, true, false, }, new int[]{1, 0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[5], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.SOUTH, Direction.EAST, },
                    new String[]{"C00B32M102112", "C00B32M102112", "C00B32M102112", "C20B32M102112", }, new Position[][]{new Position[]{new Position(3,2)}, new Position[]{new Position(3,2)}, new Position[]{new Position(3,2)}, new Position[]{new Position(2,0)}, },
                    new boolean[]{false, false, false, true, }, new int[]{1, 1, 1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[6], new Direction[]{Direction.WEST, Direction.NORTH, Direction.WEST, Direction.EAST, Direction.WEST, },
                    new String[]{"C24B32M132334", "C22B32M132334", "C22B12M132334", "C22B32M132334", "C22B12M132334", }, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(2,2)}, new Position[]{new Position(1,2)}, new Position[]{new Position(3,2)}, new Position[]{new Position(1,2)}, },
                    new boolean[]{true, true, true, true, true, }, new int[]{0, 0, 1, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[7], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.EAST, Direction.SOUTH, },
                    new String[]{"C22B42G02M411232", "C22B42G02M411232", "C22B42G02M411232", "C22B42G02M411232", }, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(2,2)}, new Position[]{new Position(2,2)}, new Position[]{new Position(0,2)}, },
                    new boolean[]{false, false, false, false, }, new int[]{2, 0, 0, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[8], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C24B40G20M103021", "C24B40G22M103021", "C24B40G20M103021", }, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(2,2)}, new Position[]{new Position(2,0)}, },
                    new boolean[]{true, true, true, }, new int[]{2, 2, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[9], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.EAST, },
                    new String[]{"C40B20G02M103001", "C00B20G02M103001", "C00B40G02M103001", }, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(0,0)}, new Position[]{new Position(4,0)}, },
                    new boolean[]{true, true, true, }, new int[]{2, 0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[10], new Direction[]{Direction.WEST, Direction.WEST, Direction.EAST, Direction.WEST, },
                    new String[]{"C42B30G00M102133", "C42B30G00M102133", "C42B30G20M102133", "C42B00G20M102133", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(4,2)}, new Position[]{new Position(2,0)}, new Position[]{new Position(0,0)}, },
                    new boolean[]{false, false, true, true, }, new int[]{1, 0, 2, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[11], new Direction[]{Direction.EAST, Direction.NORTH, },
                    new String[]{"C42B12G22M132434", "C42B12G22M132434", }, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(4,2)}, },
                    new boolean[]{true, false, }, new int[]{2, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[12], new Direction[]{Direction.WEST, Direction.EAST, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C01M301122FW31", "C21M301122FW31", "C23M301122FW31", "C21M301122FW31", }, new Position[][]{new Position[]{new Position(0,1)}, new Position[]{new Position(2,1)}, new Position[]{new Position(2,3)}, new Position[]{new Position(2,1)}, },
                    new boolean[]{true, true, true, true, }, new int[]{0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[13], new Direction[]{Direction.WEST, Direction.WEST, Direction.SOUTH, Direction.SOUTH, Direction.EAST, },
                    new String[]{"C30M122242FE21", "C30M122242FE21", "C30M122242FE21", "C30M122242FE21", "C30M122242FE21", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[14], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.SOUTH, Direction.WEST, Direction.SOUTH, },
                    new String[]{"C43M202223FS31", "C43M202223FS31", "C43M202223FS31", "C43M202223FS31", "C43M202223FS31", }, new Position[][]{new Position[]{new Position(4,3)}, new Position[]{new Position(4,3)}, new Position[]{new Position(4,3)}, new Position[]{new Position(4,3)}, new Position[]{new Position(4,3)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[15], new Direction[]{Direction.NORTH, Direction.EAST, Direction.WEST, Direction.EAST, Direction.WEST, },
                    new String[]{"C10M010223FN13", "C10M010223FN13", "C10M010223FN13", "C10M010223FN13", "C10M010223FN13", }, new Position[][]{new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[16], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C01M410242FN10S31", "C03M410242FN10S31", "C01M410242FN10S31", "C03M410242FN10S31", "C01M410242FN10S31", }, new Position[][]{new Position[]{new Position(0,1)}, new Position[]{new Position(0,3)}, new Position[]{new Position(0,1)}, new Position[]{new Position(0,3)}, new Position[]{new Position(0,1)}, },
                    new boolean[]{true, true, true, true, true, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[17], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.SOUTH, Direction.WEST, Direction.WEST, },
                    new String[]{"C34M023204FW21E13", "C34M023204FW21E13", "C34M023204FW21E13", "C34M023204FW21E13", "C34M023204FW21E13", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[18], new Direction[]{Direction.SOUTH, Direction.SOUTH, Direction.EAST, Direction.NORTH, },
                    new String[]{"C21M204223FS33", "C21M204223FS33", "C21M204223FS33", "C21M204223FS33", }, new Position[][]{new Position[]{new Position(2,1)}, new Position[]{new Position(2,1)}, new Position[]{new Position(2,1)}, new Position[]{new Position(2,1)}, },
                    new boolean[]{false, false, false, false, }, new int[]{0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[19], new Direction[]{Direction.WEST, Direction.WEST, },
                    new String[]{"C10M022223FN13", "C10M022223FN13", }, new Position[][]{new Position[]{new Position(1,0)}, new Position[]{new Position(1,0)}, },
                    new boolean[]{false, false, }, new int[]{0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[20], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.SOUTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C30M023223FE11", "C30M023223FE11", "C30M023223FE11", "C30M023223FE11", "C30M023223FE11", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[21], new Direction[]{Direction.NORTH, Direction.SOUTH, },
                    new String[]{"C13M142444FS32W33", "C13M142444FS32W33", }, new Position[][]{new Position[]{new Position(1,3)}, new Position[]{new Position(1,3)}, },
                    new boolean[]{false, false, }, new int[]{0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[22], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C30M403224FE11N13", "C30M403224FE11N13", "C30M403224FE11N13", "C30M403224FE11N13", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, new Position[]{new Position(3,0)}, },
                    new boolean[]{false, false, false, false, }, new int[]{0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[23], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, },
                    new String[]{"C11M402122FS32W33", "C41M402122FS32W33", "C11M402122FS32W33", }, new Position[][]{new Position[]{new Position(1,1)}, new Position[]{new Position(4,1)}, new Position[]{new Position(1,1)}, },
                    new boolean[]{true, true, true, }, new int[]{0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[24], new Direction[]{Direction.WEST, Direction.SOUTH, },
                    new String[]{"B33G03M414244FS11N30", "B33G03M414244FS11N30", }, new Position[][]{new Position[]{new Position(3,3)}, new Position[]{new Position(0,3)}, },
                    new boolean[]{false, false, }, new int[]{0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[25], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"B31G22M1013FE11", "B31G22M1013FE11", "B31G22M1013FE11", }, new Position[][]{new Position[]{new Position(3,1)}, new Position[]{new Position(2,2)}, new Position[]{new Position(2,2)}, },
                    new boolean[]{false, false, false, }, new int[]{0, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[26], new Direction[]{Direction.SOUTH, Direction.SOUTH, },
                    new String[]{"B31G02M400304FE11S13", "B31G02M400304FE11S13", }, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(3,1)}, },
                    new boolean[]{true, false, }, new int[]{1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[27], new Direction[]{Direction.WEST, Direction.WEST, Direction.SOUTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"B22G11M3203FN12", "B02G11M3203FN12", "B02G14M3203FN12", "B04G14M3203FN12", "B02G14M3203FN12", }, new Position[][]{new Position[]{new Position(2,2)}, new Position[]{new Position(0,2)}, new Position[]{new Position(1,4)}, new Position[]{new Position(0,4)}, new Position[]{new Position(0,2)}, },
                    new boolean[]{true, true, true, true, true, }, new int[]{0, 0, 1, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[28], new Direction[]{Direction.NORTH, Direction.WEST, },
                    new String[]{"B30G44M24FS32", "B30G44M24FS32", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(4,4)}, },
                    new boolean[]{true, false, }, new int[]{0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[29], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.EAST, Direction.SOUTH, },
                    new String[]{"B13G24M42FS11W31", "B13G24M42FS11W31", "B13G24M42FS11W31", "B13G24M42FS11W31", }, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, },
                    new boolean[]{false, false, false, false, }, new int[]{1, 1, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[30], new Direction[]{Direction.NORTH, Direction.EAST, },
                    new String[]{"B40G32M102022FS34", "B40G32M102022FS34", }, new Position[][]{new Position[]{new Position(4,0)}, new Position[]{new Position(4,0)}, },
                    new boolean[]{false, false, }, new int[]{0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[31], new Direction[]{Direction.NORTH, Direction.WEST, Direction.SOUTH, },
                    new String[]{"B44G31M012141FS11E23", "B44G31M012141FS11E23", "B44G31M012141FS11E23", }, new Position[][]{new Position[]{new Position(3,1)}, new Position[]{new Position(4,4)}, new Position[]{new Position(4,4)}, },
                    new boolean[]{false, false, false, }, new int[]{1, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[32], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.WEST, Direction.EAST, Direction.EAST, },
                    new String[]{"B31G44M323334FE11N13", "B31G44M323334FE11N13", "B31G24M323334FE11N13", "B31G24M323334FE11N13", "B31G24M323334FE11N13", }, new Position[][]{new Position[]{new Position(3,1)}, new Position[]{new Position(3,1)}, new Position[]{new Position(2,4)}, new Position[]{new Position(3,1)}, new Position[]{new Position(3,1)}, },
                    new boolean[]{false, false, true, false, false, }, new int[]{0, 0, 1, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[33], new Direction[]{Direction.EAST, Direction.SOUTH, Direction.NORTH, Direction.SOUTH, },
                    new String[]{"B14G20M4021FS11N30", "B14G22M4021FS11N30", "B14G20M4021FS11N30", "B14G22M4021FS11N30", }, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(2,2)}, new Position[]{new Position(2,0)}, new Position[]{new Position(2,2)}, },
                    new boolean[]{true, true, true, true, }, new int[]{1, 1, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[34], new Direction[]{Direction.NORTH, Direction.WEST, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"B30G31M1102FE13N33", "B30G31M1102FE13N33", "B32G31M1102FE13N33", "B30G31M1102FE13N33", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(3,1)}, new Position[]{new Position(3,2)}, new Position[]{new Position(3,0)}, },
                    new boolean[]{true, false, true, true, }, new int[]{0, 1, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[35], new Direction[]{Direction.EAST, Direction.NORTH, Direction.SOUTH, },
                    new String[]{"B00G33M301222FE21", "B00G33M301222FE21", "B00G33M301222FE21", }, new Position[][]{new Position[]{new Position(3,3)}, new Position[]{new Position(0,0)}, new Position[]{new Position(0,0)}, },
                    new boolean[]{false, false, false, }, new int[]{1, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[36], new Direction[]{Direction.SOUTH, Direction.NORTH, Direction.EAST, Direction.WEST, Direction.EAST, },
                    new String[]{"C24M012204FS11E13", "C24M012204FS11E13", "C24M012204FS11E13", "C24M012204FS11E13", "C24M012204FS11E13", }, new Position[][]{new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, new Position[]{new Position(2,4)}, },
                    new boolean[]{false, false, false, false, false, }, new int[]{0, 0, 0, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[37], new Direction[]{Direction.EAST, Direction.EAST, },
                    new String[]{"C44G03M202122FS11N30", "C44G03M202122FS11N30", }, new Position[][]{new Position[]{new Position(0,3)}, new Position[]{new Position(0,3)}, },
                    new boolean[]{false, false, }, new int[]{1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[38], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C32B10G22M304233FE11W31", "C34B10G22M304233FE11W31", "C34B12G22M304233FE11W31", "C32B12G22M304233FE11W31", }, new Position[][]{new Position[]{new Position(1,0)}, new Position[]{new Position(3,4)}, new Position[]{new Position(1,2)}, new Position[]{new Position(3,2)}, },
                    new boolean[]{true, true, true, true, }, new int[]{1, 0, 1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[39], new Direction[]{Direction.NORTH, Direction.SOUTH, Direction.NORTH, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C31G11M201204FE13N33", "C31G14M201204FE13N33", "C31G11M201204FE13N33", "C31G14M201204FE13N33", "C31G11M201204FE13N33", }, new Position[][]{new Position[]{new Position(1,1)}, new Position[]{new Position(1,4)}, new Position[]{new Position(1,1)}, new Position[]{new Position(1,4)}, new Position[]{new Position(1,1)}, },
                    new boolean[]{true, true, true, true, true, }, new int[]{1, 1, 1, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[40], new Direction[]{Direction.EAST, Direction.WEST, },
                    new String[]{"C24B34M212304FS11", "C24B14M212304FS11", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(1,4)}, },
                    new boolean[]{true, true, }, new int[]{1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[41], new Direction[]{Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, },
                    new String[]{"C00B43M213132FS12", "C00B43M213132FS12", "C00B43M213132FS12", "C00B43M213132FS12", }, new Position[][]{new Position[]{new Position(4,3)}, new Position[]{new Position(0,0)}, new Position[]{new Position(4,3)}, new Position[]{new Position(4,3)}, },
                    new boolean[]{false, false, false, false, }, new int[]{1, 0, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[42], new Direction[]{Direction.SOUTH, Direction.NORTH, Direction.WEST, },
                    new String[]{"B41G13M122232FW21", "B41G11M122232FW21", "B01G11M122232FW21", }, new Position[][]{new Position[]{new Position(1,3)}, new Position[]{new Position(1,1)}, new Position[]{new Position(0,1)}, },
                    new boolean[]{true, true, true, }, new int[]{1, 1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[43], new Direction[]{Direction.WEST, Direction.EAST, },
                    new String[]{"C13B01G14M223344FN11W21", "C13B41G14M223344FN11W21", }, new Position[][]{new Position[]{new Position(0,1)}, new Position[]{new Position(4,1)}, },
                    new boolean[]{true, true, }, new int[]{1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[44], new Direction[]{Direction.EAST, Direction.WEST, },
                    new String[]{"C42B23G03M00FW21S34", "C42B23G03M00FW21S34", }, new Position[][]{new Position[]{new Position(4,2)}, new Position[]{new Position(4,2)}, },
                    new boolean[]{false, false, }, new int[]{0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[45], new Direction[]{Direction.EAST, Direction.NORTH, Direction.EAST, Direction.NORTH, },
                    new String[]{"C02B34G03M100111FN30", "C02B34G03M100111FN30", "C02B34G03M100111FN30", "C00B34G03M100111FN30", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, new Position[]{new Position(3,4)}, new Position[]{new Position(0,0)}, },
                    new boolean[]{false, false, false, true, }, new int[]{1, 1, 1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[46], new Direction[]{Direction.NORTH, Direction.WEST, Direction.SOUTH, Direction.EAST, },
                    new String[]{"C20B41M223223FE31", "C20B11M223223FE31", "C24B11M223223FE31", "C24B41M223223FE31", }, new Position[][]{new Position[]{new Position(2,0)}, new Position[]{new Position(1,1)}, new Position[]{new Position(2,4)}, new Position[]{new Position(4,1)}, },
                    new boolean[]{true, true, true, true, }, new int[]{0, 1, 0, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[47], new Direction[]{Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C20B03G40M301121", "C20B03G40M301121", }, new Position[][]{new Position[]{new Position(0,3)}, new Position[]{new Position(0,3)}, },
                    new boolean[]{false, false, }, new int[]{1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[48], new Direction[]{Direction.WEST, Direction.NORTH, Direction.NORTH, Direction.SOUTH, },
                    new String[]{"C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", "C40B31G34M2244FE11S13", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(4,0)}, new Position[]{new Position(3,4)}, new Position[]{new Position(4,0)}, },
                    new boolean[]{false, false, false, false, }, new int[]{2, 0, 2, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[49], new Direction[]{Direction.WEST, Direction.SOUTH, Direction.NORTH, },
                    new String[]{"C00B21G20M100122FW03", "C00B23G20M100122FW03", "C00B21G20M100122FW03", }, new Position[][]{new Position[]{new Position(0,0)}, new Position[]{new Position(2,3)}, new Position[]{new Position(2,1)}, },
                    new boolean[]{true, true, true, }, new int[]{0, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[50], new Direction[]{Direction.SOUTH, Direction.EAST, Direction.EAST, Direction.WEST, Direction.NORTH, },
                    new String[]{"C02B01G23M042444FE21S32", "C02B01G23M042444FE21S32", "C02B41G23M042444FE21S32", "C02B01G23M042444FE21S32", "C02B01G23M042444FE21S32", }, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(2,3)}, new Position[]{new Position(4,1)}, new Position[]{new Position(0,1)}, new Position[]{new Position(2,3)}, },
                    new boolean[]{true, false, true, true, false, }, new int[]{0, 2, 1, 1, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[51], new Direction[]{Direction.NORTH, Direction.EAST, },
                    new String[]{"C31B42G34M402304FE11S13", "C31B42G34M402304FE11S13", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(4,2)}, },
                    new boolean[]{false, false, }, new int[]{2, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[52], new Direction[]{Direction.SOUTH, Direction.SOUTH, },
                    new String[]{"C41B30G10M010204FN11W13", "C41B30G14M010204FN11W13", }, new Position[][]{new Position[]{new Position(3,0)}, new Position[]{new Position(1,4)}, },
                    new boolean[]{false, true, }, new int[]{1, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[53], new Direction[]{Direction.NORTH, Direction.EAST, },
                    new String[]{"C10B34G14M200113FS31", "C40B34G14M200113FS31", }, new Position[][]{new Position[]{new Position(3,4)}, new Position[]{new Position(4,0)}, },
                    new boolean[]{false, true, }, new int[]{1, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[54], new Direction[]{Direction.EAST, Direction.WEST, Direction.WEST, Direction.EAST, },
                    new String[]{"C22B03G43M210444FS33", "C22B03G23M210444FS33", "C22B03G23M210444FS33", "C22B03G23M210444FS33", }, new Position[][]{new Position[]{new Position(4,3)}, new Position[]{new Position(2,3)}, new Position[]{new Position(0,3)}, new Position[]{new Position(0,3)}, },
                    new boolean[]{true, true, false, false, }, new int[]{2, 2, 1, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[55], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.WEST, Direction.SOUTH, },
                    new String[]{"C03B14G21M402243FE11N31", "C03B14G41M402243FE11N31", "C03B14G41M402243FE11N31", "C03B14G21M402243FE11N31", "C03B14G21M402243FE11N31", }, new Position[][]{new Position[]{new Position(2,1)}, new Position[]{new Position(4,1)}, new Position[]{new Position(1,4)}, new Position[]{new Position(2,1)}, new Position[]{new Position(1,4)}, },
                    new boolean[]{true, true, false, true, false, }, new int[]{2, 2, 1, 2, 1, }),
            new MakeMoveResult(Challenge.CHALLENGES[56], new Direction[]{Direction.SOUTH, Direction.SOUTH, },
                    new String[]{"C00B11G13M221444FW31E43", "C00B11G13M221444FW31E43", }, new Position[][]{new Position[]{new Position(1,3)}, new Position[]{new Position(1,3)}, },
                    new boolean[]{false, false, }, new int[]{2, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[57], new Direction[]{Direction.WEST, Direction.EAST, Direction.WEST, Direction.NORTH, },
                    new String[]{"C22B02G10M404204FN31W33", "C22B02G10M404204FN31W33", "C22B02G10M404204FN31W33", "C22B02G10M404204FN31W33", }, new Position[][]{new Position[]{new Position(0,2)}, new Position[]{new Position(0,2)}, new Position[]{new Position(2,2)}, new Position[]{new Position(1,0)}, },
                    new boolean[]{false, false, false, false, }, new int[]{1, 1, 0, 2, }),
            new MakeMoveResult(Challenge.CHALLENGES[58], new Direction[]{Direction.SOUTH, Direction.WEST, Direction.NORTH, Direction.WEST, },
                    new String[]{"C31B42G03M302244FE11W23", "C31B42G03M302244FE11W23", "C31B42G03M302244FE11W23", "C31B42G03M302244FE11W23", }, new Position[][]{new Position[]{new Position(0,3)}, new Position[]{new Position(0,3)}, new Position[]{new Position(3,1)}, new Position[]{new Position(3,1)}, },
                    new boolean[]{false, false, false, false, }, new int[]{2, 2, 0, 0, }),
            new MakeMoveResult(Challenge.CHALLENGES[59], new Direction[]{Direction.EAST, Direction.NORTH, },
                    new String[]{"C31B42G34M302203FE11", "C31B42G34M302203FE11", }, new Position[][]{new Position[]{new Position(3,1)}, new Position[]{new Position(3,1)}, },
                    new boolean[]{false, false, }, new int[]{0, 0, }),
    };

}
